// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCphCaqzsqsElvBNDazzIE4SQ2yo-Iagg',
    appId: '1:14908313922:web:a4e7728b25fb45cdb178db',
    messagingSenderId: '14908313922',
    projectId: 'aim-assist-a3b61',
    authDomain: 'aim-assist-a3b61.firebaseapp.com',
    storageBucket: 'aim-assist-a3b61.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKl-o0Nfq930m5OL31wf1T9gJBYyO_AkU',
    appId: '1:14908313922:android:07af9eed27af4c5bb178db',
    messagingSenderId: '14908313922',
    projectId: 'aim-assist-a3b61',
    storageBucket: 'aim-assist-a3b61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL9BgTaUSNVktXe5II5Y4cLrgTCVvAYhI',
    appId: '1:14908313922:ios:31d44ddb1fe81f6fb178db',
    messagingSenderId: '14908313922',
    projectId: 'aim-assist-a3b61',
    storageBucket: 'aim-assist-a3b61.appspot.com',
    iosClientId: '14908313922-tds7u5di2ma327hfteb2q37jatmskg77.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginsys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL9BgTaUSNVktXe5II5Y4cLrgTCVvAYhI',
    appId: '1:14908313922:ios:31d44ddb1fe81f6fb178db',
    messagingSenderId: '14908313922',
    projectId: 'aim-assist-a3b61',
    storageBucket: 'aim-assist-a3b61.appspot.com',
    iosClientId: '14908313922-tds7u5di2ma327hfteb2q37jatmskg77.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginsys',
  );
}
